services:
  picpay_web:
     build:
       dockerfile: container-build/web/Dockerfile
       context: .
     environment:
       - MYSQL_DATABASE=picpay_db
       - MYSQL_USER=picpay_db
       - MYSQL_PASSWORD=654321
       - MYSQL_HOST=localhost
     image: tecnando/dev_web
     container_name: picpay_web
     volumes:
       - ".:/var/www"
     ports:
       - "8080:80"
  tecnando_db:
    environment:
       - MYSQL_DATABASE=picpay_db
       - MYSQL_USER=picpay_db
       - MYSQL_PASSWORD=654321
       - MYSQL_ROOT_PASSWORD=654321
    image: mysql:8.1.0
    container_name: picpay_db
    ports:
      - "33065:3306"
